name: hrrr_data
channels:
  - conda-forge
dependencies:
  - python>=3.11
  - pip
  - pipreqs
  - pre-commit
  - ruff
  - mypy
  - mamba
  - cartopy
  - matplotlib
  - ncl
  - netcdf4
  - numpy
  - pygrib
  - requests
  - s3fs
  - xarray
  - jupyter_client
  - jupyter_core
  - notebook
  - ipykernel
  - pip:
      - git+https://github.com/jankazil/hrrr-data
